server:
  port: 8081
  address: 0.0.0.0
  servlet:
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: chathub
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${chathub.mysql.ip}:${chathub.mysql.port}/${chathub.mysql.db}?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${chathub.mysql.username}
    password: ${chathub.mysql.password}
    hikari:
      # 最小空闲连接数量
      minimum-idle: 3
      # 最大连接池数量
      maximum-pool-size: 10
      # 连接超时时间
      max-lifetime: 30000
      connection-test-query: SELECT 1
  rabbitmq:
    host: ${chathub.rabbitmq.host}
    port: ${chathub.rabbitmq.port}
    username: ${chathub.rabbitmq.username}
    password: ${chathub.rabbitmq.password}
  redis:
    host: ${chathub.redis.host}
    port: ${chathub.redis.port}
    database: 0
    timeout: 1800000
    password: ${chathub.redis.password}
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
oss:
  enabled: true
  type: minio
  endpoint: ${chathub.minio.endpoint}
  access-key: ${chathub.minio.access-key}
  secret-key: ${chathub.minio.secret-key}
  bucket-name: ${chathub.minio.bucket-name}